name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout gp-pages branch
        uses: actions/checkout@v2
        with:
          ref: gp-pages

      - name: merge master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: gp_pages
          github_token: ${{ secrets.ACCESS_TOKEN }}

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: iartist93/jolie
          TARGET_BRANCH: docs
          BUILD_SCRIPT: yarn && yarn docs:build
          BUILD_DIR: docs/.vuepress/dist
          CNAME: https://iartist93.github.io/jolie/
